# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prijava', '0003_auto_20161224_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplikant',
            name='godina_rodjenja',
            field=models.DateField(default=None),
        ),
    ]
