# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='ESN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(max_length=2000)),
                ('web_stranica', models.CharField(blank=True, max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=20)),
                ('twitter', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ESN_Sarajevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(max_length=2000)),
                ('web_stranica', models.CharField(blank=True, max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=20)),
                ('twitter', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Novost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=30)),
                ('datum', models.DateField()),
                ('sadrzaj', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='O_projektu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stavka', models.CharField(max_length=20)),
                ('opis', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_puno', models.CharField(max_length=30)),
                ('titula', models.CharField(max_length=30)),
                ('biografija', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Trening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
                ('opis', models.TextField(max_length=500)),
                ('dodatni_opis', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='trener',
            name='trening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hard_podaci.Trening'),
        ),
    ]
