# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hard_podaci', '0003_auto_20161108_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
