# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_podaci', '0004_delete_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kompanija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='Kompanije_Logo')),
            ],
        ),
    ]
