# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_podaci', '0005_kompanija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medij',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='Medij_Logo')),
                ('web_stranica', models.CharField(blank=True, max_length=30)),
                ('twitter', models.CharField(blank=True, max_length=16)),
                ('facebook', models.CharField(blank=True, max_length=30)),
                ('paket', models.CharField(blank=True, choices=[('g', 'godišnji'), ('z', 'zlatni'), ('s', 'srebrni')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='kompanija',
            name='facebook',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='kompanija',
            name='paket',
            field=models.CharField(blank=True, choices=[('g', 'godišnji'), ('z', 'zlatni'), ('s', 'srebrni')], max_length=1),
        ),
        migrations.AddField(
            model_name='kompanija',
            name='twitter',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='kompanija',
            name='web_stranica',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='trener',
            name='facebook',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
