# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_podaci', '0006_auto_20161108_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompanija',
            name='paket',
            field=models.CharField(blank=True, choices=[('g', 'Godišnji'), ('z', 'Zlatni'), ('s', 'Srebrni')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medij',
            name='paket',
            field=models.CharField(blank=True, choices=[('g', 'Godišnji'), ('z', 'Zlatni'), ('s', 'Srebrni')], max_length=1),
        ),
    ]
