# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_podaci', '0007_auto_20161109_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompanija',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
