# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_podaci', '0008_auto_20161115_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='trener',
            name='slika',
            field=models.ImageField(default='opcija2.jpg', upload_to='Trener_Logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trening',
            name='slika',
            field=models.ImageField(default='opcija2.jpg', upload_to='Treninzi_Logo'),
            preserve_default=False,
        ),
    ]
