# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_podaci', '0009_auto_20161218_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trener',
            name='slika',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='trening',
            name='slika',
            field=models.FileField(upload_to=''),
        ),
    ]
