# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_podaci', '0010_auto_20161218_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ESN_Sarajevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(max_length=10000)),
            ],
        ),
    ]
