# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_podaci', '0012_auto_20161219_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sazetak', models.CharField(max_length=225)),
                ('opis', models.TextField()),
                ('datum_objave', models.DateField()),
            ],
        ),
    ]
